const C = {
    SEARCH_CITY: 'SEARCH_CITY',
    ADD_CITY: 'ADD_CITY',
    REMOVE_CITY: 'REMOVE_CITY',
    SELECT_CITY: 'SELECT_CITY',
    CLEAR_CITY: 'CLEAR_CITY',
    RECEIVED_CITY: 'RECEIVED_CITY',
    INIT_CITIES: 'INIT_CITIES',
    SHOW_SEARCH: 'SHOW_SEARCH',
};

export { C };
